name: Deploy to Environment

# Triggers, on specific branches
on:
  push:
    branches:
      - main
      - release
      - develop
    
env:
  # Where to find reusable bicep, etc. files
  THIS_DIRECTORY: '.github/workflows'
  WORKFLOW_BICEP_DIRECTORY: '.github/workflows/bicep'
  LIB_BICEP_DIRECTORY: '.github/workflows/lib/azure/bicep/recipes' # LIB_REPO_DEPLOYMENT_DIR1
 
# Running on one runner:      
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: NP
    env:
      FOO: BAR