
# An Action needs a Name, Triggers, Jobs.
# aided by variables:
name: LetsGo

env:
  branch: main
  resourceGroupName: TemplateDeploymentRG
  defaultLocation : uksouth
  bicepfilePath: ./SOURCE/Storage-Template/main.bicep    
# Triggering 3 choices of triggers. On a specific branch.
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  JobUno:
    runs-on: ubuntu-latest
    steps:  
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  JobDuo:
    runs-on: ubuntu-latest
    steps:  
      - run: echo "🎉 The job is run by ${{ github.actor }}."
  JobTres:
    runs-on: ubuntu-latest
    steps:  
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."      
  JobQuatro:
    runs-on: ubuntu-latest
    steps:  
      - run: echo "...let's go"
      - run: echo "🔎 macro... ${{env.defaultLocation}}."
      - run: echo "🔎 macro... ${{env.branch}}."
      - run: echo "🔎 token... ${{secrets.GITHUB_TOKEN}}."
      - run: echo "🔎 lets go to the ... ${{vars.foo}}."
